version: '3.4'

services:
  php:
    build: .
    image: php:8.0
    volumes:
      - ./:/var/www/html

networks:
  default:
      driver:
          bridge
      ipam:
        config:
        - subnet: "${DOCKER_SUBNET:-172.35.0.0/24}"
